Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "petclinic-prod"
  config.vm.boot_timeout = 600

  config.vm.network "forwarded_port",
    guest: 22,
    host: 2222,
    id: "ssh",
    host_ip: "127.0.0.1"

  config.vm.network "forwarded_port",
    guest: 8080,
    host: 8080,
    id: "petclinic",
    host_ip: "127.0.0.1"

  config.vm.network "forwarded_port",
    guest: 9100,
    host: 9101,
    id: "node_exporter",
    host_ip: "127.0.0.1"

end
