Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "petclinic-prod"

  config.vm.network "forwarded_port",
    guest: 22,
    host: 2222,
    id: "ssh"

  config.vm.network "forwarded_port",
    guest: 8080,
    host: 8082,
    id: "petclinic"

  config.vm.network "forwarded_port",
    guest: 9100,
    host: 9101,
    id: "node_exporter"
end
