services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: petclinic-app
    ports:
      - "8080:8080"
    networks:
      - miniproject-net

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - zap_reports:/var/jenkins_home/workspace/pipeline/zap/reports
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/ssh/vagrant_private_key:/run/secrets/vagrant_private_key:ro
    networks:
      - miniproject-net

  sonarqube:
    build:
      context: ./sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - miniproject-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - miniproject-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - miniproject-net

  zap:
    build:
      context: ./zap/
    #image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap
    #command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true
    volumes:
      - zap_reports:/zap/reports
      #- type: bind
      #  source: ./zap/reports
      #  target: /zap/reports
    ports:
      - "8090:8090"
    networks:
      - miniproject-net

networks:
  miniproject-net:
    name: miniproject-net

volumes:
  jenkins_home:
  grafana_data:
  zap_reports:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
