{
 "title": "Jenkins",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Jenkins Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "jenkins_job_count_value" }
   ]
  },
  {
   "title": "Executors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "jenkins_executor_count_value" }
   ]
  },
  {
   "title": "Build Queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  {
   "title": "Build Results",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jenkins_runs_success_total", "legendFormat": "Successful" },
    { "expr": "jenkins_runs_failure_total", "legendFormat": "Failed" },
    { "expr": "jenkins_runs_unstable_total", "legendFormat": "Unstable" }
   ]
  }
 ]
}