global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "petclinic"
    metrics_path: /actuator/prometheus
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/petclinic-targets.yml
        refresh_interval: 5s

  - job_name: "petclinic_vm_node"
    static_configs:
      - targets: ["host.docker.internal:9101"]
        labels:
          environment: "production"
          role: "vm_host"

  - job_name: "jenkins"
    metrics_path: /prometheus/
    static_configs:
      - targets: ["jenkins:8080"]
